Repository jenkinsci/http-request-plugin, pull requests merged in 2021-04, with the labels that each got.

#54 Store response headers in TreeMap with case insensitive comparator
  src/main/java/jenkins/plugins/http_request/ResponseContentSupplier.java
  src/test/java/jenkins/plugins/http_request/HttpRequestTest.java
Labels: bug

#56 [JENKINS-65458] - Add descriptions to HTTP Request Plugin arguments
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-acceptType.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-authentication.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-consoleLogResponseBody.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-contentType.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-httpMode.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-httpProxy.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-ignoreSslErrors.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-multipartName.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-outputFile.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-quiet.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-requestBody.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-responseHandle.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-timeout.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-uploadFile.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-url.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-useSystemProperties.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-validResponseCodes.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-validResponseContent.html
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/help-wrapAsMultipart.html
Labels: enhancement

#48 Allow to use ntlm auth
  src/main/java/jenkins/plugins/http_request/HttpRequest.java
  src/main/java/jenkins/plugins/http_request/HttpRequestExecution.java
  src/main/java/jenkins/plugins/http_request/HttpRequestStep.java
  src/main/java/jenkins/plugins/http_request/auth/CredentialNtlmAuthentication.java
Labels: enhancement

#55 Allow payload body in GET requests
  src/main/java/jenkins/plugins/http_request/util/HttpBodyGet.java
  src/main/java/jenkins/plugins/http_request/util/HttpClientUtil.java
Labels: enhancement

#46 Provide an ability to specify proxy authentication
  src/main/java/jenkins/plugins/http_request/HttpRequest.java
  src/main/java/jenkins/plugins/http_request/HttpRequestExecution.java
  src/main/java/jenkins/plugins/http_request/HttpRequestStep.java
  src/main/java/jenkins/plugins/http_request/auth/BasicDigestAuthentication.java
  src/main/java/jenkins/plugins/http_request/auth/CredentialBasicAuthentication.java
  src/main/resources/jenkins/plugins/http_request/HttpRequestStep/config.jelly
  src/main/webapp/help-proxyAuthentication.html
  src/test/java/jenkins/plugins/http_request/HttpRequestStepTest.java
  src/test/java/jenkins/plugins/http_request/HttpRequestTest.java
Labels: enhancement

#57 Enable Release Drafter for changelog automation
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#58 Enable Dependabot in the repository
  .github/dependabot.yml
Labels: chore
